apiVersion: batch/v1
kind: Job
metadata:
  name: ingestor
  namespace: ingenium
spec:
  template:
    spec:
      containers:
        - name: ingestor
          image: alpaca-historical:latest
          command:
          - --name alpaca-historical-cpng
          - --symbol CPNG
          - --timeframe 1h
      restartPolicy: Never
