apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-portfolio
  namespace: ingenium
spec:
  selector:
    matchLabels:
      app: example-portfolio
  template:
    metadata:
      labels:
        app: example-portfolio
    spec:
      containers:
      - name: portfolio
        image: example-portfolio:0.12
        command:
          - /portfolio
          - -broker
          - http://kafka-broker-ingress.knative-eventing.svc.cluster.local/ingenium/broker
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-portfolio
  namespace: ingenium
spec:
  selector:
    app: example-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: example-portfolio
  namespace: ingenium
  annotations:
     kafka.eventing.knative.dev/delivery.order: ordered
spec:
  broker: broker
  filter:
    attributes:
      type: ingenium.strategy.signal
  subscriber:
    ref:
     apiVersion: v1
     kind: Service
     name: example-portfolio