apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsi-strategy
  namespace: ingenium
spec:
  selector:
    matchLabels:
      app: rsi-strategy
  template:
    metadata:
      labels:
        app: rsi-strategy
    spec:
      containers:
      - name: strategy
        image: rsi-strategy:latest
        command:
          - /strategy
          - --symbol
          - CPNG
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
